### ISSUE TITLE
Issue with New Frimware in Darwin-OP

### ISSUE THREAD

**Issue by meisamb** [UPenn-RoboCup/UPennalizers#18]
Hi
I can't run Upennalizers on my Darwin-OP because the robot being twisted.
Our MX-28 actuators are using new frimware.
I have changed "Config_OP_Robot.lua" to support new frimware, but my issue didn't solve.

In addition when we run "run_dcm.lua" it returns 0 value for joint's positions.

Should i change anything else?

**Comment by TechnoX** [comment]
I think we have the same issue, I was able to find this page when browsing the wiki: 
https://github.com/UPenn-RoboCup/UPennalizers/wiki/Darwin-Motor-Calibration

I did "Uncomment this line under 'for testing' : dcm.actuator.readType[1]=1;--Read ALL --- Save and exit"
Then I got values from all the servos when I run "run_dcm.lua"

My main concern is that I can't find the test_bias.lua.
All my offsets seems to be wrong, because when I run the sample program the robot is being twisted badly.

**Comment by meisamb** [comment]
thanks TechnoX, 
Motor calibration didn't help me. but my issue solved by downloading original sources by this command in Linux:

> > git clone https://github.com/UPenn-RoboCup/UPennalizers.git
> > I have just uncomment the section for new firmware in"Player/Config/Config_OP_Robot.lua".
> > Now robot can works as I expected. 
> > I think that i have downloaded one of the branches not original codes and that's why it doesn't work properly.
